#!/usr/bin/env tsx
/**
 * Generate JSON Schema (draft 2020-12) from Zod SSOT.
 *
 * Source: `packages/contracts/src/domain/go-accelerator.ts` (goAcceleratorSchemas)
 * Target: `contracts/json-schema/go-accelerator/*.json`
 *
 * Usage:
 *   pnpm --filter @trapmap/contracts exec tsx scripts/generate-json-schema.ts        # write
 *   pnpm --filter @trapmap/contracts exec tsx scripts/generate-json-schema.ts --check # fail on drift
 *
 * CI gate: `pnpm generate:contracts --check` + `git diff --exit-code` mirrors
 * the OpenAPI drift pattern (hand-crafted spec + generated types + CI check).
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { goAcceleratorSchemas } from '../src/domain/go-accelerator.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const OUT_DIR = join(ROOT, 'contracts', 'json-schema', 'go-accelerator');

type SchemaMap = Record<string, { toJSONSchema: () => unknown }>;

function toSortedJson(value: unknown): string {
  return JSON.stringify(value, null, 2) + '\n';
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const check = args.includes('--check');

  const schemas = goAcceleratorSchemas as unknown as SchemaMap;
  const entries = Object.entries(schemas);

  await mkdir(OUT_DIR, { recursive: true });

  // Write each schema's JSON Schema
  const generated = new Map<string, string>();
  for (const [name, schema] of entries) {
    const jsonSchema = schema.toJSONSchema() as Record<string, unknown>;
    // Ensure $schema is draft 2020-12 (Zod 4 emits it) and add title
    if (!jsonSchema.$schema) {
      jsonSchema.$schema = 'https://json-schema.org/draft/2020-12/schema';
    }
    // Title helps quicktype/go-jsonschema naming
    if (!jsonSchema.title) {
      jsonSchema.title = name;
    }
    // x-go-type hint for manual mapping (payload -> json.RawMessage)
    const content = toSortedJson(jsonSchema);
    generated.set(name, content);
  }

  // Also write an index that lists all schemas (for humans)
  const indexContent = toSortedJson({
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'go-accelerator-index',
    description:
      'Index of go-accelerator Zod->JSON Schema (contracts SSOT). Generated by packages/contracts/scripts/generate-json-schema.ts — do not edit manually.',
    generatedAt: new Date().toISOString(),
    schemas: Object.fromEntries(entries.map(([k]) => [k, `./${k}.json`])),
  });
  generated.set('_index', indexContent);

  if (check) {
    let drift = false;
    for (const [name, content] of generated) {
      const filePath = join(OUT_DIR, `${name}.json`);
      let existing = '';
      try {
        existing = await readFile(filePath, 'utf8');
      } catch {
        console.error(`[generate:contracts] missing ${filePath} — run without --check to generate`);
        drift = true;
        continue;
      }
      // Normalize: compare parsed JSON stringified (ignore generatedAt in index)
      if (name === '_index') {
        const a = JSON.parse(existing) as Record<string, unknown>;
        const b = JSON.parse(content) as Record<string, unknown>;
        // generatedAt is volatile — compare everything else
        const { generatedAt: _a, ...restA } = a as { generatedAt?: unknown };
        const { generatedAt: _b, ...restB } = b as { generatedAt?: unknown };
        if (JSON.stringify(restA) !== JSON.stringify(restB)) {
          console.error(`[generate:contracts] drift in ${name}.json`);
          drift = true;
        }
        continue;
      }
      if (existing !== content) {
        console.error(
          `[generate:contracts] drift in ${name}.json — run pnpm generate:contracts to regenerate`,
        );
        // Show first diff line
        const eLines = existing.split('\n');
        const gLines = content.split('\n');
        for (let i = 0; i < Math.min(eLines.length, gLines.length); i++) {
          if (eLines[i] !== gLines[i]) {
            console.error(
              `  line ${i + 1}: expected ${JSON.stringify(gLines[i])} got ${JSON.stringify(eLines[i])}`,
            );
            break;
          }
        }
        drift = true;
      }
    }
    if (drift) {
      console.error(
        `\n[generate:contracts] JSON Schema drift detected. Run: pnpm generate:contracts`,
      );
      process.exit(1);
    }
    console.log(`[generate:contracts] check ok — ${generated.size} schemas in sync (${OUT_DIR})`);
    return;
  }

  for (const [name, content] of generated) {
    const filePath = join(OUT_DIR, `${name}.json`);
    await writeFile(filePath, content, 'utf8');
    console.log(`[generate:contracts] wrote ${filePath}`);
  }
  console.log(`[generate:contracts] done — ${generated.size} files in ${OUT_DIR}`);
}

main().catch((err) => {
  console.error('[generate:contracts] failed', err);
  process.exit(1);
});
