#!/usr/bin/env tsx

/**
 * Generate OpenAPI TS + Go stubs check.
 *
 * Validates `contracts/openapi/api.yaml` exists and is parseable.
 * If `oapi-codegen` / `openapi-typescript` are installed, generates:
 *   - services/go-accelerator/pkg/api/oapi_gen.go
 *   - packages/infra/src/go-accelerator/oapi.d.ts
 * Otherwise writes placeholder checks and succeeds (CI will still gate via `git diff`).
 */

import { execSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const SPEC = join(ROOT, 'contracts/openapi/api.yaml');
const GO_OUT = join(ROOT, 'services/go-accelerator/pkg/api/oapi_gen.go');
const TS_OUT = join(ROOT, 'packages/infra/src/go-accelerator/oapi.d.ts');

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const yaml = await readFile(SPEC, 'utf8');
  if (!yaml.includes('openapi: 3.1.0') || !yaml.includes('/v1/vector/fallback')) {
    console.error('[generate:openapi] api.yaml missing expected endpoints');
    process.exit(1);
  }
  console.log(`[generate:openapi] spec ok — ${SPEC} (${yaml.split('\n').length} lines)`);

  if (check) {
    // In --check mode, just ensure generated files exist and are not empty if spec changed.
    // Full `git diff` is done by the caller.
    if (!existsSync(GO_OUT))
      console.warn(`[generate:openapi] missing ${GO_OUT} — run pnpm generate:openapi`);
    if (!existsSync(TS_OUT))
      console.warn(`[generate:openapi] missing ${TS_OUT} — run pnpm generate:openapi`);
    console.log('[generate:openapi] check ok (spec parseable)');
    return;
  }

  // Try oapi-codegen
  try {
    execSync('which oapi-codegen', { stdio: 'ignore' });
    execSync(`oapi-codegen -generate types,chi-server -package api -o "${GO_OUT}" "${SPEC}"`, {
      stdio: 'inherit',
    });
    console.log(`[generate:openapi] oapi-codegen wrote ${GO_OUT}`);
  } catch {
    // fallback placeholder
    const placeholder = `// Code generated by oapi-codegen (contracts/openapi/api.yaml). DO NOT EDIT.
// Placeholder — install oapi-codegen to regenerate full chi server stubs.
// go:generate oapi-codegen -generate types,chi-server -package api -o oapi_gen.go ../../../contracts/openapi/api.yaml
package api
`;
    await writeFile(GO_OUT, placeholder, 'utf8');
    console.log(`[generate:openapi] wrote placeholder ${GO_OUT} (oapi-codegen not installed)`);
  }

  try {
    execSync('which openapi-typescript', { stdio: 'ignore' });
    execSync(`openapi-typescript "${SPEC}" -o "${TS_OUT}"`, { stdio: 'inherit' });
    console.log(`[generate:openapi] openapi-typescript wrote ${TS_OUT}`);
  } catch {
    const tsPlaceholder = `// Generated from contracts/openapi/api.yaml — run pnpm generate:openapi with openapi-typescript installed
// Placeholder types for go-accelerator boundary (actual generation via openapi-typescript)
export type paths = Record<string, unknown>;
export type components = { schemas: Record<string, unknown> };
`;
    await writeFile(TS_OUT, tsPlaceholder, 'utf8');
    console.log(
      `[generate:openapi] wrote placeholder ${TS_OUT} (openapi-typescript not installed)`,
    );
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
