// Code generated by contracts SSOT (packages/contracts/src/domain -> contracts/json-schema) via z.toJSONSchema().
// Go structs mirror Zod schemas; payload uses json.RawMessage for z.unknown(). DO NOT EDIT manually — run pnpm generate:contracts.

package api

import "encoding/json"

type HealthResponse struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Version string `json:"version"`
}

type KnowledgeReadRequest struct {
	Query  string `json:"query"`
	Limit  *int   `json:"limit,omitempty"`
	QueryTokens []string `json:"queryTokens,omitempty"`
}

type RetrievalScoreEntry struct {
	ID            string   `json:"id"`
	Scope         string   `json:"scope"`
	Labels        []string `json:"labels"`
	RequiredLevel int      `json:"requiredLevel"`
	Shortcut      string   `json:"shortcut"`
	Detail        string   `json:"detail"`
	Score         float64  `json:"score,omitempty"`
}

type RankingEntry struct {
	ID                 string             `json:"id"`
	SemanticScore      float64            `json:"semanticScore"`
	KeywordScore       float64            `json:"keywordScore"`
	GraphScore         *float64           `json:"graphScore,omitempty"`
	ChannelScores      map[string]float64 `json:"channelScores"`
	CombinedScore      float64            `json:"combinedScore"`
	TokenMatches       []TokenMatch       `json:"tokenMatches"`
	Channels           []string           `json:"channels"`
	PreRerankScore     float64            `json:"preRerankScore"`
	FinalScore         float64            `json:"finalScore"`
	BoundaryScoreDelta *float64           `json:"boundaryScoreDelta,omitempty"`
	DecayMultiplier    *float64           `json:"decayMultiplier,omitempty"`
	Labels             []string           `json:"labels"`
	Scope              string             `json:"scope"`
	Shortcut           string             `json:"shortcut"`
	Detail             string             `json:"detail"`
	DecayState         *string            `json:"decayState,omitempty"`
	Boundary           *Boundary          `json:"boundary,omitempty"`
}

type TokenMatch struct {
	Token  string   `json:"token"`
	Fields []string `json:"fields"`
}

type Boundary struct {
	Context    []string    `json:"context,omitempty"`
	Exclusions []Exclusion `json:"exclusions,omitempty"`
}

type Exclusion struct {
	Kind        string `json:"kind"`
	Description string `json:"description"`
}

type RankingBatchRequest struct {
	Entries          []RankingEntry `json:"entries"`
	SemanticEntries  []RankingEntry `json:"semanticEntries,omitempty"`
	KeywordEntries   []RankingEntry `json:"keywordEntries,omitempty"`
	GraphEntries     []RankingEntry `json:"graphEntries,omitempty"`
	QueryTokens      []string       `json:"queryTokens,omitempty"`
	MaxCandidates    *int           `json:"maxCandidates,omitempty"`
	BoundaryContext  *BoundaryContext `json:"boundaryContext,omitempty"`
}

type RankingBatchResponse struct {
	Merged []RankingEntry `json:"merged"`
}

type BoundaryContext struct {
	Contexts []string `json:"contexts"`
	Platform *string  `json:"platform,omitempty"`
}

type KnowledgeReadResponse struct {
	Entries   []RankingEntry `json:"entries"`
	Summary   string         `json:"summary"`
	Citations []Citation     `json:"citations"`
}

type Citation struct {
	ID     string `json:"id"`
	Scope  string `json:"scope"`
	Detail string `json:"detail"`
}

type VectorCosineRequest struct {
	A []float64 `json:"a"`
	B []float64 `json:"b"`
}

type VectorCosineResponse struct {
	Similarity float64 `json:"similarity"`
}

type BatchCosineRequest struct {
	Query   []float64   `json:"query"`
	Vectors [][]float64 `json:"vectors"`
}

type BatchCosineResponse struct {
	Scores []float64 `json:"scores"`
}

type CanonicalHashRequest struct {
	Payload json.RawMessage `json:"payload"`
}

type CanonicalHashResponse struct {
	Canonical string `json:"canonical"`
	Hash      string `json:"hash"`
}
