server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: trapmap-docker
    static_configs:
      - targets:
          - localhost
        labels:
          service: trapmap
          environment: local-docker
          job: trapmap-docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            eventName: eventName
            requestId: requestId
            traceId: traceId
            serviceName: serviceName
            route: route
            method: method
            statusCode: statusCode
