// Code generated by oapi-codegen (contracts/openapi/api.yaml). DO NOT EDIT.
// Placeholder — install oapi-codegen to regenerate full chi server stubs.
// go:generate oapi-codegen -generate types,chi-server -package api -o oapi_gen.go ../../../contracts/openapi/api.yaml
package api
