// Code generated by contracts SSOT (packages/contracts/src/domain/go-accelerator.ts -> contracts/json-schema/go-accelerator/*.json) via z.toJSONSchema(). DO NOT EDIT frequencies manually — run `pnpm generate:contracts` and keep this file in sync (CI: pnpm generate:contracts:check).
// Go struct tags are the source for JSON wire; Zod schemas enforce the same constraints (sha256Hex pattern, finite floats, etc.). Payload uses json.RawMessage to preserve arbitrary JSON (maps to z.unknown()).

package api

import "encoding/json"

type HealthResponse struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Version string `json:"version"`
}

type CanonicalHashRequest struct {
	Payload json.RawMessage `json:"payload"`
}

type CanonicalHashResponse struct {
	Canonical string `json:"canonical"`
	Hash      string `json:"hash"`
}

type VectorCosineRequest struct {
	A []float64 `json:"a"`
	B []float64 `json:"b"`
}

type VectorCosineResponse struct {
	Similarity float64 `json:"similarity"`
	NormA      float64 `json:"normA"`
	NormB      float64 `json:"normB"`
}

type BatchCosineRequest struct {
	Query   []float64   `json:"query"`
	Vectors [][]float64 `json:"vectors"`
}

type BatchCosineResponse struct {
	Scores []float64 `json:"scores"`
}

type TokenizeRequest struct {
	Text      string `json:"text"`
	MaxTokens *int   `json:"maxTokens,omitempty"`
	ChunkSize *int   `json:"chunkSize,omitempty"`
	Overlap   *int   `json:"overlap,omitempty"`
}

type TokenizeResponse struct {
	Tokens []string `json:"tokens"`
	Chunks []string `json:"chunks"`
	Count  int      `json:"count"`
}

type RetrievalScoreEntry struct {
	ID            string   `json:"id"`
	Scope         string   `json:"scope"`
	Labels        []string `json:"labels"`
	RequiredLevel int      `json:"requiredLevel"`
	Shortcut      string   `json:"shortcut"`
	Detail        string   `json:"detail"`
	Score         float64  `json:"score,omitempty"`
}

type RetrievalScoreRequest struct {
	Entries []RetrievalScoreEntry `json:"entries"`
	Query   string                `json:"query"`
	Filters struct {
		Labels []string `json:"labels"`
		Scopes []string `json:"scopes"`
	} `json:"filters"`
	Limit *int `json:"limit,omitempty"`
}

type RetrievalScoreResponse struct {
	GlobalConstraints []RetrievalScoreEntry `json:"globalConstraints"`
	ProjectKnowledge  []RetrievalScoreEntry `json:"projectKnowledge"`
	Reason            string                `json:"reason"`
}

type GeneCandidate struct {
	GeneID          string  `json:"geneId"`
	Title           string  `json:"title"`
	SemanticScore   float64 `json:"semanticScore"`
	KeywordScore    float64 `json:"keywordScore"`
	ExactMatch      bool    `json:"exactSignalMatch"`
	ErrorTextMatch  bool    `json:"errorTextMatch"`
	BoundaryMatch   bool    `json:"boundaryMatch"`
	FreshValidation bool    `json:"freshValidation"`
	BroadMatch      bool    `json:"broadMatch"`
	SourceKind      string  `json:"sourceKind"`
	ValidationCount *int    `json:"validationCount,omitempty"`
}

type GeneSelectRequest struct {
	Candidates []GeneCandidate `json:"candidates"`
	Query      string          `json:"query"`
	MaxResults *int            `json:"maxResults,omitempty"`
}

type ScoredGene struct {
	GeneID string   `json:"geneId"`
	Score  float64  `json:"score"`
	Reasons []string `json:"reasons"`
}

type GeneSelectResponse struct {
	Selected []ScoredGene `json:"selected"`
	Warnings []string     `json:"warnings,omitempty"`
}

type FallbackVectorRequest struct {
	Text string `json:"text"`
	Dim  *int   `json:"dim,omitempty"`
}

type FallbackVectorResponse struct {
	Vector []float64 `json:"vector"`
	Dim    int       `json:"dim"`
}

// P1: ranking / keyword / dedup

type TokenMatch struct {
	Token  string   `json:"token"`
	Fields []string `json:"fields"`
}

type RankingEntry struct {
	ID                string             `json:"id"`
	SemanticScore     float64            `json:"semanticScore"`
	KeywordScore      float64            `json:"keywordScore"`
	GraphScore        *float64           `json:"graphScore,omitempty"`
	ChannelScores     map[string]float64 `json:"channelScores"`
	CombinedScore     float64            `json:"combinedScore"`
	TokenMatches      []TokenMatch       `json:"tokenMatches"`
	Channels          []string           `json:"channels"`
	PreRerankScore    float64            `json:"preRerankScore"`
	FinalScore        float64            `json:"finalScore"`
	BoundaryScoreDelta *float64          `json:"boundaryScoreDelta,omitempty"`
	DecayMultiplier   *float64           `json:"decayMultiplier,omitempty"`
	Labels            []string           `json:"labels"`
	Scope             string             `json:"scope"`
	Shortcut          string             `json:"shortcut"`
	Detail            string             `json:"detail"`
	DecayState        *string            `json:"decayState,omitempty"`
	Boundary          *RankingBoundary   `json:"boundary,omitempty"`
}

type RankingBoundary struct {
	Context    []string `json:"context,omitempty"`
	Exclusions []struct {
		Kind        string `json:"kind"`
		Description string `json:"description"`
	} `json:"exclusions,omitempty"`
}

type RankingBatchRequest struct {
	Entries          []RankingEntry `json:"entries"`
	SemanticEntries  []RankingEntry `json:"semanticEntries,omitempty"`
	KeywordEntries   []RankingEntry `json:"keywordEntries,omitempty"`
	GraphEntries     []RankingEntry `json:"graphEntries,omitempty"`
	QueryTokens      []string       `json:"queryTokens,omitempty"`
	MaxCandidates    *int           `json:"maxCandidates,omitempty"`
	BoundaryContext  *struct {
		Contexts []string `json:"contexts"`
		Platform *string  `json:"platform,omitempty"`
	} `json:"boundaryContext,omitempty"`
}

type RankingBatchResponse struct {
	Merged []RankingEntry `json:"merged"`
}

type KeywordScoreRequest struct {
	QueryTokens []string `json:"queryTokens"`
	EntryTokens struct {
		Shortcut []string `json:"shortcut"`
		Detail   []string `json:"detail"`
		Labels   []string `json:"labels"`
	} `json:"entryTokens"`
}

type KeywordScoreResponse struct {
	Score        float64      `json:"score"`
	TokenMatches []TokenMatch `json:"tokenMatches"`
}

type DedupFingerprintRequest struct {
	Parts []string `json:"parts"`
}

type DedupFingerprintResponse struct {
	Fingerprint string `json:"fingerprint"`
}

type DedupSimilarityRequest struct {
	LeftTokens  []string `json:"leftTokens"`
	RightTokens []string `json:"rightTokens"`
}

type DedupBatchSimilarityRequest struct {
	LeftTokens   []string   `json:"leftTokens"`
	RightTokensList [][]string `json:"rightTokensList"`
}

type DedupBatchSimilarityResponse struct {
	Similarities []float64 `json:"similarities"`
	SharedCounts []int     `json:"sharedCounts"`
	UnionCounts  []int     `json:"unionCounts"`
}

type DedupSimilarityResponse struct {
	Similarity  float64 `json:"similarity"`
	SharedCount int     `json:"sharedCount"`
	UnionCount  int     `json:"unionCount"`
}

// P2: gene derive batch
type GeneDeriveTrapInput struct {
	TrapID           string `json:"trapId"`
	TrapText         string `json:"trapText"`
	DerivationUnitID string `json:"derivationUnitId"`
}

type GeneDeriveBatchRequest struct {
	Traps []GeneDeriveTrapInput `json:"traps"`
}

type GeneDeriveSections struct {
	MATCH    []string `json:"MATCH"`
	GOAL     []string `json:"GOAL"`
	STRATEGY []string `json:"STRATEGY"`
	AVOID    []string `json:"AVOID"`
	VERIFY   []string `json:"VERIFY"`
}

type GeneDeriveResult struct {
	TrapID           string             `json:"trapId"`
	DerivationUnitID string             `json:"derivationUnitId"`
	Sections         GeneDeriveSections `json:"sections"`
	ContentHash      string             `json:"contentHash"`
	SourceHash       string             `json:"sourceHash"`
}

type GeneDeriveBatchResponse struct {
	Results []GeneDeriveResult `json:"results"`
}
