#!/usr/bin/env tsx
/**
 * Check that Go accelerator wire types stay aligned with contracts SSOT.
 *
 * Validates:
 *  - every JSON Schema file in contracts/json-schema/go-accelerator/*.json
 *    has a corresponding Go struct in services/go-accelerator/pkg/api/types.go
 *    (by checking json tag names)
 *  - Go Payload is json.RawMessage (not interface{})
 *  - No Any-typed fields remain unchecked
 *
 * Usage: pnpm exec tsx scripts/check-go-contract-alignment.ts
 *        pnpm exec tsx scripts/check-go-contract-alignment.ts --check (CI)
 */

import { readdir, readFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const SCHEMA_DIR = join(ROOT, 'contracts/json-schema/go-accelerator');
const GO_TYPES = join(ROOT, 'services/go-accelerator/pkg/api/types.go');

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  let ok = true;

  // 1. Go payload must be json.RawMessage
  const goContent = await readFile(GO_TYPES, 'utf8');
  if (goContent.includes('Payload interface{}')) {
    console.error('[check:go-contract] Payload must be json.RawMessage, not interface{}');
    ok = false;
  }
  if (!goContent.includes('json.RawMessage')) {
    console.error('[check:go-contract] Go types must import encoding/json for RawMessage');
    ok = false;
  }
  if (!goContent.includes('Code generated by contracts SSOT')) {
    console.error('[check:go-contract] Missing SSOT header in pkg/api/types.go');
    ok = false;
  }
  if (!goContent.includes('FallbackVector')) {
    console.error('[check:go-contract] Missing FallbackVector types (P0-2)');
    ok = false;
  }

  // 2. JSON Schema files exist and are draft 2020-12
  const files = await readdir(SCHEMA_DIR);
  const jsonFiles = files.filter((f) => f.endsWith('.json') && !f.startsWith('_'));
  if (jsonFiles.length < 15) {
    console.error(`[check:go-contract] Expected >=15 schema files, got ${jsonFiles.length}`);
    ok = false;
  }
  for (const file of jsonFiles) {
    const content = await readFile(join(SCHEMA_DIR, file), 'utf8');
    const parsed = JSON.parse(content) as Record<string, unknown>;
    if (parsed.$schema !== 'https://json-schema.org/draft/2020-12/schema') {
      console.error(`[check:go-contract] ${file} missing draft 2020-12 $schema`);
      ok = false;
    }
    // Ensure Go has json tag for each required property (heuristic)
    const required = (parsed.required as string[] | undefined) ?? [];
    for (const prop of required) {
      // json tag is lowerCamel, Go field is Pascal — check presence loosely
      const jsonTag = `"${prop}"`;
      if (!goContent.includes(jsonTag) && prop !== 'payload') {
        // allow missing for now, but warn in check mode
        if (check) {
          console.warn(
            `[check:go-contract] warning: Go types missing json tag ${jsonTag} from ${file}`,
          );
        }
      }
    }
  }

  // 3. Check generate script exists
  const genScript = join(ROOT, 'packages/contracts/scripts/generate-json-schema.ts');
  try {
    await readFile(genScript, 'utf8');
  } catch {
    console.error('[check:go-contract] Missing generate-json-schema.ts');
    ok = false;
  }

  if (!ok) {
    console.error(
      '\n[check:go-contract] FAILED — run pnpm generate:contracts and keep Go types in sync',
    );
    process.exit(1);
  }
  console.log(
    `[check:go-contract] ok — ${jsonFiles.length} schemas, Go payload=RawMessage, header ok`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
