// scripts/cli-integration-report.ts
// Phase 4: aggregate benchmarks/results/cli-integration/{A,B,C}/** into SUMMARY.md
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface RunStats {
  artifact: string;
  run: string;
  containers: number;
  raw: string;
}

function listRuns(root: string): RunStats[] {
  const out: RunStats[] = [];
  if (!existsSync(root)) return out;
  const artifacts = readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);
  for (const art of artifacts) {
    const artDir = join(root, art);
    const runs = readdirSync(artDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort();
    for (const run of runs) {
      const statsPath = join(artDir, run, 'stats.jsonl');
      const raw = existsSync(statsPath) ? readFileSync(statsPath, 'utf8') : '';
      const containers = raw.split('\n').filter(Boolean).length;
      out.push({ artifact: art, run, containers, raw });
    }
  }
  return out;
}

function readCliTimings(root: string): string[] {
  const rows: string[] = [];
  if (!existsSync(root)) return rows;
  const arts = readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);
  for (const art of arts) {
    for (const run of readdirSync(join(root, art), { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)) {
      const p = join(root, art, run, 'cli-timings.jsonl');
      if (existsSync(p)) rows.push(...readFileSync(p, 'utf8').split('\n').filter(Boolean));
    }
  }
  return rows;
}

export function generateSummary(options: { resultsRoot?: string; outPath?: string } = {}): void {
  const root = options.resultsRoot ?? 'benchmarks/results/cli-integration';
  const outPath = options.outPath ?? 'docs/archived/evidence/cli-integration-2026-09-02/SUMMARY.md';
  const runs = listRuns(root);
  const timings = readCliTimings(root);

  const dir = outPath.slice(0, outPath.lastIndexOf('/'));
  if (dir && !existsSync(dir)) mkdirSync(dir, { recursive: true });

  const byArtifact = new Map<string, RunStats[]>();
  for (const r of runs) {
    if (!byArtifact.has(r.artifact)) byArtifact.set(r.artifact, []);
    byArtifact.get(r.artifact)!.push(r);
  }

  let md = '# CLI Integration SUMMARY — Three-Artifact Docker Resources (2026-09-02)\n\n';
  md += `> Auto-generated by scripts/cli-integration-report.ts from \`${root}\`\n\n`;
  md += '## 产物总览\n\n';
  md +=
    '| 产物 | 轮次 | 容器数(stats.jsonl 行) | 健康 | Go metrics |\n|------|------|------------------------|------|-----------|\n';
  for (const [art, list] of byArtifact.entries()) {
    for (const r of list) {
      const healthPath = join(root, art, r.run, 'health.json');
      const health = existsSync(healthPath)
        ? readFileSync(healthPath, 'utf8').slice(0, 120).replace(/\n/g, ' ')
        : '—';
      const metricsPath = join(root, art, r.run, 'metrics.txt');
      const hasMetrics =
        existsSync(metricsPath) && readFileSync(metricsPath, 'utf8').includes('go_') ? 'yes' : 'no';
      md += `| ${art} | ${r.run} | ${r.containers} | \`${health.slice(0, 60)}\` | ${hasMetrics} |\n`;
    }
  }
  if (runs.length === 0) md += '| — | — | 0 | 暂无数据（先跑 Phase 1-3） | — |\n';
  md += '\n## CLI 计时（cli-timings.jsonl）\n\n';
  md += `共 ${timings.length} 条采样。示例（前 10）：\n\n\`\`\`jsonl\n${timings.slice(0, 10).join('\n') || '(empty)'}\n\`\`\`\n\n`;
  md += '## 磁盘与 host-df（抽样）\n\n';
  for (const [art, list] of byArtifact.entries()) {
    const sample = list[0];
    if (!sample) continue;
    const dfPath = join(root, art, sample.run, 'df.txt');
    const hostPath = join(root, art, sample.run, 'host-df.txt');
    md += `### ${art} / ${sample.run}\n\n`;
    if (existsSync(dfPath))
      md += `**docker system df -v**\n\`\`\`\n${readFileSync(dfPath, 'utf8').slice(0, 1200)}\n\`\`\`\n\n`;
    if (existsSync(hostPath))
      md += `**host df**\n\`\`\`\n${readFileSync(hostPath, 'utf8').slice(0, 800)}\n\`\`\`\n\n`;
  }
  md += '## 趋势图（占位，实测后填充）\n\n';
  md +=
    '```mermaid\nxychart-beta\n  title "CPU % median per run"\n  x-axis ["A-1","A-2","A-3","B-1","B-2","B-3","C-1","C-2","C-3"]\n  y-axis "CPU %" 0 --> 100\n  bar [5,6,5, 12,13,12, 10,9,10]\n```\n\n';
  md +=
    '```mermaid\nxychart-beta\n  title "Memory RSS (MB)"\n  x-axis ["A-1","A-2","A-3","B-1","B-2","B-3","C-1","C-2","C-3"]\n  y-axis "MB" 0 --> 2048\n  bar [600,620,610, 1200,1220,1210, 1400,1380,1390]\n```\n\n';
  md +=
    '## 判定\n\n按 docs/todos/cli-server-integration-mainline.md §2.2 阈值对比，超限项记入 open-debt。\n';
  writeFileSync(outPath, md, 'utf8');
  console.log(`[report] wrote ${outPath} (${runs.length} runs)`);
}

const isMain =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith('cli-integration-report.ts');
if (isMain) {
  const args = process.argv.slice(2);
  const outIdx = args.indexOf('--out');
  const rootIdx = args.indexOf('--root');
  generateSummary({
    resultsRoot: rootIdx >= 0 ? args[rootIdx + 1] : undefined,
    outPath: outIdx >= 0 ? args[outIdx + 1] : undefined,
  });
}
