time="2026-09-02T16:54:54+08:00" level=warning msg="The \"OPENAI_API_KEY\" variable is not set. Defaulting to a blank string."
time="2026-09-02T16:54:54+08:00" level=warning msg="The \"OPENAI_API_KEY\" variable is not set. Defaulting to a blank string."
name: trap-map
services:
  postgres:
    container_name: trapmap-postgres
    environment:
      POSTGRES_DB: trapmap
      POSTGRES_PASSWORD: trapmap
      POSTGRES_USER: trapmap
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U trapmap -d trapmap
      timeout: 5s
      interval: 10s
      retries: 5
    image: pgvector/pgvector:pg16
    networks:
      trapmap-distributed: null
    ports:
      - mode: ingress
        target: 5432
        published: "5434"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume: {}
networks:
  trapmap-distributed:
    name: trapmap-distributed
    external: true
volumes:
  postgres_data:
    name: trap-map_postgres_data
